import { initContract } from "@ts-rest/core";
import { z } from "zod";

import {
  apiKeySchema,
  badRequestSchema,
  createApiKeyResponseSchema,
  createApiKeySchema,
  createDocumentSchema,
  createProjectSchema,
  createTaskSchema,
  documentContentSchema,
  documentSchema,
  documentTypeSchema,
  errorSchema,
  healthSchema,
  projectSchema,
  searchResultSchema,
  taskSchema,
  updateDocumentContentSchema,
  updateDocumentSchema,
  updateProjectSchema,
  updateTaskSchema,
} from "./schemas.js";
import * as s from "./schemas.js";

const c = initContract();

export const apiContract = c.router(
  {
    health: {
      method: "GET",
      path: "/health",
      responses: {
        200: healthSchema,
      },
      summary: "Health check",
    },
    listProjects: {
      method: "GET",
      path: "/api/v1/projects",
      query: z.object({
        organizationId: z.string().optional(),
        area: z.string().optional(),
        status: z.string().optional(),
      }),
      responses: {
        200: z.object({ projects: z.array(projectSchema) }),
        401: errorSchema,
        403: errorSchema,
      },
      summary: "List projects",
    },
    getProject: {
      method: "GET",
      path: "/api/v1/projects/:id",
      pathParams: z.object({ id: z.string() }),
      responses: {
        200: projectSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Get project by id",
    },
    createProject: {
      method: "POST",
      path: "/api/v1/projects",
      body: createProjectSchema,
      responses: {
        201: projectSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Create project",
    },
    updateProject: {
      method: "PATCH",
      path: "/api/v1/projects/:id",
      pathParams: z.object({ id: z.string() }),
      body: updateProjectSchema,
      responses: {
        200: projectSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Update project",
    },
    deleteProject: {
      method: "DELETE",
      path: "/api/v1/projects/:id",
      pathParams: z.object({ id: z.string() }),
      body: null,
      responses: {
        204: c.noBody(),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Soft-delete project",
    },
    listTasks: {
      method: "GET",
      path: "/api/v1/tasks",
      query: z.object({
        projectId: z.string().optional(),
        contactId: z.string().optional(),
        assigneeId: z.string().optional(),
        status: z.string().optional(),
        inbox: z.coerce.boolean().optional(),
      }),
      responses: {
        200: z.object({ tasks: z.array(taskSchema) }),
        401: errorSchema,
        403: errorSchema,
      },
      summary: "List tasks",
    },
    getTask: {
      method: "GET",
      path: "/api/v1/tasks/:id",
      pathParams: z.object({ id: z.string() }),
      responses: {
        200: taskSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Get task by id",
    },
    createTask: {
      method: "POST",
      path: "/api/v1/tasks",
      body: createTaskSchema,
      responses: {
        201: taskSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Create task",
    },
    updateTask: {
      method: "PATCH",
      path: "/api/v1/tasks/:id",
      pathParams: z.object({ id: z.string() }),
      body: updateTaskSchema,
      responses: {
        200: taskSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Update task",
    },
    deleteTask: {
      method: "DELETE",
      path: "/api/v1/tasks/:id",
      pathParams: z.object({ id: z.string() }),
      body: null,
      responses: {
        204: c.noBody(),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Soft-delete task",
    },
    listApiKeys: {
      method: "GET",
      path: "/api/v1/api-keys",
      responses: {
        200: z.object({ apiKeys: z.array(apiKeySchema) }),
        401: errorSchema,
      },
      summary: "List API keys (Clerk session)",
    },
    createApiKey: {
      method: "POST",
      path: "/api/v1/api-keys",
      body: createApiKeySchema,
      responses: {
        201: createApiKeyResponseSchema,
        400: badRequestSchema,
        401: errorSchema,
      },
      summary: "Create API key (Clerk session; secret shown once)",
    },
    revokeApiKey: {
      method: "DELETE",
      path: "/api/v1/api-keys/:id",
      pathParams: z.object({ id: z.string() }),
      body: null,
      responses: {
        204: c.noBody(),
        401: errorSchema,
        404: errorSchema,
      },
      summary: "Revoke API key (Clerk session)",
    },
    listDocuments: {
      method: "GET",
      path: "/api/v1/documents",
      query: z.object({
        type: documentTypeSchema.optional(),
        projectId: z.string().optional(),
      }),
      responses: {
        200: z.object({ documents: z.array(documentSchema) }),
        401: errorSchema,
        403: errorSchema,
      },
      summary: "List documents",
    },
    getDocument: {
      method: "GET",
      path: "/api/v1/documents/:id",
      pathParams: z.object({ id: z.string() }),
      responses: {
        200: documentSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Get document metadata",
    },
    createDocument: {
      method: "POST",
      path: "/api/v1/documents",
      body: createDocumentSchema,
      responses: {
        201: documentSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
        503: errorSchema,
      },
      summary: "Create document metadata (optional initial content)",
    },
    updateDocument: {
      method: "PATCH",
      path: "/api/v1/documents/:id",
      pathParams: z.object({ id: z.string() }),
      body: updateDocumentSchema,
      responses: {
        200: documentSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
        503: errorSchema,
      },
      summary: "Update document metadata",
    },
    deleteDocument: {
      method: "DELETE",
      path: "/api/v1/documents/:id",
      pathParams: z.object({ id: z.string() }),
      body: null,
      responses: {
        204: c.noBody(),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Soft-delete document",
    },
    getDocumentContent: {
      method: "GET",
      path: "/api/v1/documents/:id/content",
      pathParams: z.object({ id: z.string() }),
      responses: {
        200: documentContentSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Get document body from object storage",
    },
    updateDocumentContent: {
      method: "PATCH",
      path: "/api/v1/documents/:id/content",
      pathParams: z.object({ id: z.string() }),
      body: updateDocumentContentSchema,
      responses: {
        200: documentContentSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
        409: errorSchema,
        503: errorSchema,
      },
      summary: "Write document body to object storage",
    },
    search: {
      method: "GET",
      path: "/api/v1/search",
      query: z.object({
        q: z.string().min(1).max(500),
        type: documentTypeSchema.optional(),
        projectId: z.string().optional(),
        limit: z.coerce.number().int().min(1).max(50).optional(),
      }),
      responses: {
        200: z.object({ results: z.array(searchResultSchema) }),
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Search documents by title, path, and snippet",
    },
    getProjectRelations: {
      method: "GET",
      path: "/api/v1/projects/:id/relations",
      pathParams: s.idParamsSchema,
      responses: { 200: s.projectRelationsSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get project relations",
    },
    listDueTasks: {
      method: "GET",
      path: "/api/v1/tasks/due",
      query: z.object({ before: z.string().datetime().optional() }),
      responses: { 200: z.object({ tasks: z.array(taskSchema) }), 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "List tasks due before a date",
    },
    listInboxTasks: {
      method: "GET",
      path: "/api/v1/tasks/inbox",
      responses: { 200: z.object({ tasks: z.array(taskSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List inbox tasks",
    },
    getTaskRelations: {
      method: "GET",
      path: "/api/v1/tasks/:id/relations",
      pathParams: s.idParamsSchema,
      responses: { 200: s.taskRelationsSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get task relations",
    },
    batchUpdateTasks: {
      method: "POST",
      path: "/api/v1/tasks/batch",
      body: s.batchUpdateTasksSchema,
      responses: { 200: z.object({ tasks: z.array(taskSchema) }), 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Batch update tasks",
    },
    reorderTasks: {
      method: "POST",
      path: "/api/v1/tasks/reorder",
      body: s.reorderSchema,
      responses: { 200: z.object({ tasks: z.array(taskSchema) }), 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Reorder tasks",
    },
    moveTask: {
      method: "POST",
      path: "/api/v1/tasks/:id/move",
      pathParams: s.idParamsSchema,
      body: s.moveTaskSchema,
      responses: { 200: taskSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Move a task",
    },
    triageTask: {
      method: "POST",
      path: "/api/v1/tasks/:id/triage",
      pathParams: s.idParamsSchema,
      body: s.triageTaskSchema,
      responses: { 200: taskSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Triage a task",
    },
    getJournal: {
      method: "GET",
      path: "/api/v1/journal/:date",
      pathParams: z.object({ date: z.string().date() }),
      responses: { 200: documentSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get or create a journal document",
    },
    reorderDocuments: {
      method: "POST",
      path: "/api/v1/documents/reorder",
      body: s.reorderSchema,
      responses: { 200: z.object({ documents: z.array(documentSchema) }), 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Reorder documents and folders",
    },
    moveDocument: {
      method: "POST",
      path: "/api/v1/documents/:id/move",
      pathParams: s.idParamsSchema,
      body: z.object({ parentId: z.string().nullable() }),
      responses: { 200: documentSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Move a document or folder",
    },
    listOrganizations: {
      method: "GET",
      path: "/api/v1/organizations",
      responses: { 200: z.object({ organizations: z.array(s.organizationSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List organizations",
    },
    getOrganization: {
      method: "GET",
      path: "/api/v1/organizations/:id",
      pathParams: s.idParamsSchema,
      responses: { 200: s.organizationSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get an organization",
    },
    getOrganizationRelations: {
      method: "GET",
      path: "/api/v1/organizations/:id/relations",
      pathParams: s.idParamsSchema,
      responses: { 200: s.organizationRelationsSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get organization relations",
    },
    createOrganization: {
      method: "POST",
      path: "/api/v1/organizations",
      body: s.organizationInputSchema,
      responses: { 201: s.organizationSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Create an organization",
    },
    updateOrganization: {
      method: "PATCH",
      path: "/api/v1/organizations/:id",
      pathParams: s.idParamsSchema,
      body: s.updateOrganizationSchema,
      responses: { 200: s.organizationSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Update an organization",
    },
    deleteOrganization: {
      method: "DELETE",
      path: "/api/v1/organizations/:id",
      pathParams: s.idParamsSchema,
      body: null,
      responses: { 204: c.noBody(), 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Delete an organization",
    },
    listContacts: {
      method: "GET",
      path: "/api/v1/contacts",
      query: z.object({ organizationId: z.string().optional(), q: z.string().optional() }),
      responses: { 200: z.object({ contacts: z.array(s.contactSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List contacts",
    },
    getContact: {
      method: "GET",
      path: "/api/v1/contacts/:id",
      pathParams: s.idParamsSchema,
      responses: { 200: s.contactSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get a contact",
    },
    getContactRelations: {
      method: "GET",
      path: "/api/v1/contacts/:id/relations",
      pathParams: s.idParamsSchema,
      responses: { 200: s.contactRelationsSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get contact relations",
    },
    createContact: {
      method: "POST",
      path: "/api/v1/contacts",
      body: s.contactInputSchema,
      responses: { 201: s.contactSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Create a contact",
    },
    updateContact: {
      method: "PATCH",
      path: "/api/v1/contacts/:id",
      pathParams: s.idParamsSchema,
      body: s.updateContactSchema,
      responses: { 200: s.contactSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Update a contact",
    },
    deleteContact: {
      method: "DELETE",
      path: "/api/v1/contacts/:id",
      pathParams: s.idParamsSchema,
      body: null,
      responses: { 204: c.noBody(), 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Delete a contact",
    },
    listAreas: {
      method: "GET",
      path: "/api/v1/areas",
      responses: { 200: z.object({ areas: z.array(s.areaSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List areas",
    },
    getArea: {
      method: "GET",
      path: "/api/v1/areas/:id",
      pathParams: s.idParamsSchema,
      responses: { 200: s.areaSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get an area",
    },
    createArea: {
      method: "POST",
      path: "/api/v1/areas",
      body: s.areaInputSchema,
      responses: { 201: s.areaSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Create an area",
    },
    updateArea: {
      method: "PATCH",
      path: "/api/v1/areas/:id",
      pathParams: s.idParamsSchema,
      body: s.updateAreaSchema,
      responses: { 200: s.areaSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Update an area",
    },
    deleteArea: {
      method: "DELETE",
      path: "/api/v1/areas/:id",
      pathParams: s.idParamsSchema,
      body: null,
      responses: { 204: c.noBody(), 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Delete an area",
    },
    listLetters: {
      method: "GET",
      path: "/api/v1/letters",
      query: z.object({
        projectId: z.string().optional(),
        organizationId: z.string().optional(),
        contactId: z.string().optional(),
        status: z.string().optional(),
        triage: z.coerce.boolean().optional(),
      }),
      responses: { 200: z.object({ letters: z.array(s.letterSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List letters",
    },
    listLetterInbox: {
      method: "GET",
      path: "/api/v1/letters/inbox",
      responses: { 200: z.object({ letters: z.array(s.letterSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List letter inbox",
    },
    getLetter: {
      method: "GET",
      path: "/api/v1/letters/:id",
      pathParams: s.idParamsSchema,
      responses: { 200: s.letterSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get a letter",
    },
    getLetterRelations: {
      method: "GET",
      path: "/api/v1/letters/:id/relations",
      pathParams: s.idParamsSchema,
      responses: { 200: s.letterRelationsSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get letter relations",
    },
    createLetter: {
      method: "POST",
      path: "/api/v1/letters",
      body: s.letterInputSchema,
      responses: { 201: s.letterSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Create a letter",
    },
    updateLetter: {
      method: "PATCH",
      path: "/api/v1/letters/:id",
      pathParams: s.idParamsSchema,
      body: s.updateLetterSchema,
      responses: { 200: s.letterSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Update a letter",
    },
    deleteLetter: {
      method: "DELETE",
      path: "/api/v1/letters/:id",
      pathParams: s.idParamsSchema,
      body: null,
      responses: { 204: c.noBody(), 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Delete a letter",
    },
    triageLetter: {
      method: "POST",
      path: "/api/v1/letters/:id/triage",
      pathParams: s.idParamsSchema,
      body: s.triageLetterSchema,
      responses: { 200: s.letterSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Triage a letter",
    },
    putLetterPdf: {
      method: "PUT",
      path: "/api/v1/letters/:id/pdf",
      pathParams: s.idParamsSchema,
      headers: z.object({ "x-filename": z.string().optional() }),
      body: c.type<ArrayBuffer | Blob>(),
      responses: { 200: s.letterSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Upload letter PDF",
    },
    getLetterPdf: {
      method: "GET",
      path: "/api/v1/letters/:id/pdf",
      pathParams: s.idParamsSchema,
      responses: {
        200: c.otherResponse({ contentType: "application/pdf", body: c.type<Blob>() }),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Download letter PDF",
    },
    putAvatar: {
      method: "PUT",
      path: "/api/v1/avatars/:entityType/:entityId",
      pathParams: s.avatarParamsSchema,
      body: c.type<ArrayBuffer | Blob>(),
      responses: { 200: s.avatarSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Upload avatar",
    },
    getAvatar: {
      method: "GET",
      path: "/api/v1/avatars/:entityType/:entityId",
      pathParams: s.avatarParamsSchema,
      responses: {
        200: c.otherResponse({ contentType: "image/*", body: c.type<Blob>() }),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Download avatar",
    },
    getSettings: {
      method: "GET",
      path: "/api/v1/settings",
      responses: { 200: s.settingsResponseSchema, 401: errorSchema, 403: errorSchema },
      summary: "Get workspace settings",
    },
    updateSettings: {
      method: "PATCH",
      path: "/api/v1/settings",
      body: s.settingsSchema,
      responses: { 200: s.settingsResponseSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Update workspace settings",
    },
    listMentions: {
      method: "GET",
      path: "/api/v1/mentions",
      responses: { 200: z.object({ mentions: z.array(s.mentionSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List mentions",
    },
    createMention: {
      method: "POST",
      path: "/api/v1/mentions",
      body: s.createMentionSchema,
      responses: { 201: s.mentionSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Create a mention",
    },
    markMentionRead: {
      method: "POST",
      path: "/api/v1/mentions/:id/read",
      pathParams: s.idParamsSchema,
      body: null,
      responses: { 200: s.mentionSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Mark mention read",
    },
    globalSearch: {
      method: "GET",
      path: "/api/v1/global-search",
      query: z.object({ q: z.string().min(1), limit: z.coerce.number().int().min(1).max(100).optional() }),
      responses: { 200: z.object({ results: z.array(s.globalSearchResultSchema) }), 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Search all human-facing entities",
    },
    syncBootstrap: {
      method: "POST",
      path: "/api/v1/sync/bootstrap",
      body: null,
      responses: { 200: s.syncBootstrapSchema, 401: errorSchema },
      summary: "Bootstrap legacy sync",
    },
    syncPull: {
      method: "GET",
      path: "/api/v1/sync/pull",
      query: z.object({ cursor: z.coerce.number().int().nonnegative().optional() }),
      responses: { 200: s.syncPullSchema, 400: badRequestSchema, 401: errorSchema },
      summary: "Pull legacy sync events",
    },
    syncPush: {
      method: "POST",
      path: "/api/v1/sync/push",
      body: s.syncPushSchema,
      responses: { 200: s.syncPushResponseSchema, 400: badRequestSchema, 401: errorSchema, 404: errorSchema },
      summary: "Push legacy sync mutations",
    },
    getPowerSyncCredentials: {
      method: "GET",
      path: "/api/v1/powersync/token",
      responses: { 200: s.powerSyncCredentialsSchema, 401: errorSchema, 503: errorSchema },
      summary: "Get short-lived PowerSync credentials",
    },
    powerSyncWrite: {
      method: "POST",
      path: "/api/v1/powersync/write",
      body: s.powerSyncWriteSchema,
      responses: { 200: s.okSchema, 400: badRequestSchema, 401: errorSchema, 404: errorSchema },
      summary: "Apply a PowerSync write batch",
    },
  },
  {
    pathPrefix: "",
  },
);

export type ApiContract = typeof apiContract;
