packages:
  - backsteros-api
  - backsteros-app
  - backsteros-admin
  - backsteros-desktop
  - backsteros-mobile
  - backsteros-sync-demo
  - backsteros-packages/*
allowBuilds:
  '@clerk/shared': true
  '@journeyapps/wa-sqlite': true
  '@swc/core': true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
