import { initContract } from "@ts-rest/core";
import { z } from "zod";

import {
  apiKeySchema,
  badRequestSchema,
  createApiKeyResponseSchema,
  createApiKeySchema,
  updateApiKeySchema,
  createDocumentSchema,
  createProjectSchema,
  createTaskSchema,
  createTaskCommentSchema,
  createTaskActivitySchema,
  documentContentSchema,
  documentSchema,
  documentTypeSchema,
  errorSchema,
  githubBranchSchema,
  githubCommitSchema,
  githubConnectionStatusSchema,
  githubPullRequestFileSchema,
  githubPullRequestSchema,
  githubRepositorySchema,
  healthSchema,
  projectFsCreateEntryResponseSchema,
  projectFsCreateEntrySchema,
  projectFsDeleteEntryResponseSchema,
  projectFsFileSchema,
  projectFsListEntriesResponseSchema,
  projectFsWriteFileSchema,
  projectSchema,
  searchResultSchema,
  taskSchema,
  taskActivitySchema,
  taskCommentSchema,
  updateDocumentContentSchema,
  updateDocumentSchema,
  updateProjectSchema,
  updateTaskSchema,
  updateTaskCommentSchema,
  whoopDayResultSchema,
  whoopSettingsStatusSchema,
} from "./schemas.js";
import * as s from "./schemas.js";

const c = initContract();

export const apiContract = c.router(
  {
    health: {
      method: "GET",
      path: "/health",
      responses: {
        200: healthSchema,
      },
      summary: "Health check",
    },
    listProjects: {
      method: "GET",
      path: "/api/v1/projects",
      query: z.object({
        organizationId: z.string().optional(),
        area: z.string().optional(),
        status: z.string().optional(),
        type: z.string().optional(),
      }),
      responses: {
        200: z.object({ projects: z.array(projectSchema) }),
        401: errorSchema,
        403: errorSchema,
      },
      summary: "List projects",
    },
    getProject: {
      method: "GET",
      path: "/api/v1/projects/:id",
      pathParams: z.object({ id: z.string() }),
      responses: {
        200: projectSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Get project by id",
    },
    createProject: {
      method: "POST",
      path: "/api/v1/projects",
      body: createProjectSchema,
      responses: {
        201: projectSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Create project",
    },
    updateProject: {
      method: "PATCH",
      path: "/api/v1/projects/:id",
      pathParams: z.object({ id: z.string() }),
      body: updateProjectSchema,
      responses: {
        200: projectSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Update project",
    },
    deleteProject: {
      method: "DELETE",
      path: "/api/v1/projects/:id",
      pathParams: z.object({ id: z.string() }),
      body: null,
      responses: {
        204: c.noBody(),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Soft-delete project",
    },
    ensureProjectVault: {
      method: "POST",
      path: "/api/v1/projects/:id/ensure-vault",
      pathParams: z.object({ id: z.string() }),
      body: null,
      responses: {
        200: s.projectVaultEnsureSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary:
        "Ensure the project vault folder, .cursor skills, and default working directory exist",
    },
    getGithubConnectionStatus: {
      method: "GET",
      path: "/api/v1/github/status",
      responses: {
        200: githubConnectionStatusSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary:
        "GitHub OAuth connection status, scopes, and organizations for the signed-in Clerk user",
    },
    listGithubRepositories: {
      method: "GET",
      path: "/api/v1/github/repositories",
      responses: {
        200: z.object({ repositories: z.array(githubRepositorySchema) }),
        401: errorSchema,
        403: errorSchema,
      },
      summary:
        "List GitHub repositories (personal + organization) for the signed-in Clerk user",
    },
    listProjectGithubBranches: {
      method: "GET",
      path: "/api/v1/projects/:id/github/branches",
      pathParams: z.object({ id: z.string() }),
      responses: {
        200: z.object({
          repository: z.string(),
          defaultBranch: z.string().nullable(),
          branches: z.array(githubBranchSchema),
        }),
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "List branches for the project's linked GitHub repository",
    },
    listProjectGithubCommits: {
      method: "GET",
      path: "/api/v1/projects/:id/github/commits",
      pathParams: z.object({ id: z.string() }),
      query: z.object({
        branch: z.string().min(1),
        page: z.coerce.number().int().positive().optional(),
      }),
      responses: {
        200: z.object({
          repository: z.string(),
          branch: z.string(),
          page: z.number().int().positive(),
          hasMore: z.boolean(),
          commits: z.array(githubCommitSchema),
        }),
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "List commits for a branch on the project's linked GitHub repository",
    },
    getProjectGithubCommit: {
      method: "GET",
      path: "/api/v1/projects/:id/github/commits/:sha",
      pathParams: z.object({
        id: z.string(),
        sha: z.string().min(1),
      }),
      responses: {
        200: z.object({
          repository: z.string(),
          commit: githubCommitSchema,
          files: z.array(githubPullRequestFileSchema),
        }),
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary:
        "Get a single commit including changed files and patches for the project's linked repository",
    },
    listProjectGithubPullRequests: {
      method: "GET",
      path: "/api/v1/projects/:id/github/pulls",
      pathParams: z.object({ id: z.string() }),
      query: z.object({
        page: z.coerce.number().int().positive().optional(),
      }),
      responses: {
        200: z.object({
          repository: z.string(),
          page: z.number().int().positive(),
          hasMore: z.boolean(),
          pullRequests: z.array(githubPullRequestSchema),
        }),
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary:
        "List open and closed pull requests for the project's linked GitHub repository",
    },
    getProjectGithubPullRequest: {
      method: "GET",
      path: "/api/v1/projects/:id/github/pulls/:number",
      pathParams: z.object({
        id: z.string(),
        number: z.coerce.number().int().positive(),
      }),
      responses: {
        200: z.object({
          repository: z.string(),
          pullRequest: githubPullRequestSchema,
        }),
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary:
        "Get a single pull request (including description and change stats)",
    },
    listProjectGithubPullRequestCommits: {
      method: "GET",
      path: "/api/v1/projects/:id/github/pulls/:number/commits",
      pathParams: z.object({
        id: z.string(),
        number: z.coerce.number().int().positive(),
      }),
      query: z.object({
        page: z.coerce.number().int().positive().optional(),
      }),
      responses: {
        200: z.object({
          repository: z.string(),
          number: z.number().int().positive(),
          page: z.number().int().positive(),
          hasMore: z.boolean(),
          commits: z.array(githubCommitSchema),
        }),
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "List commits on a pull request for the project's linked repository",
    },
    listProjectGithubPullRequestFiles: {
      method: "GET",
      path: "/api/v1/projects/:id/github/pulls/:number/files",
      pathParams: z.object({
        id: z.string(),
        number: z.coerce.number().int().positive(),
      }),
      query: z.object({
        page: z.coerce.number().int().positive().optional(),
      }),
      responses: {
        200: z.object({
          repository: z.string(),
          number: z.number().int().positive(),
          page: z.number().int().positive(),
          hasMore: z.boolean(),
          files: z.array(githubPullRequestFileSchema),
        }),
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary:
        "List changed files (with patches) on a pull request for the project's linked repository",
    },
    listProjectFsEntries: {
      method: "GET",
      path: "/api/v1/projects/:id/fs/entries",
      pathParams: z.object({ id: z.string() }),
      query: z.object({
        path: z.string().max(4096).optional(),
      }),
      responses: {
        200: projectFsListEntriesResponseSchema,
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary:
        "List files and folders under a codebase project's local working directory",
    },
    getProjectFsFile: {
      method: "GET",
      path: "/api/v1/projects/:id/fs/file",
      pathParams: z.object({ id: z.string() }),
      query: z.object({
        path: z.string().min(1).max(4096),
      }),
      responses: {
        200: projectFsFileSchema,
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Read a text file under the project's local working directory",
    },
    writeProjectFsFile: {
      method: "PUT",
      path: "/api/v1/projects/:id/fs/file",
      pathParams: z.object({ id: z.string() }),
      body: projectFsWriteFileSchema,
      responses: {
        200: projectFsFileSchema,
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Write a text file under the project's local working directory",
    },
    createProjectFsEntry: {
      method: "POST",
      path: "/api/v1/projects/:id/fs/entries",
      pathParams: z.object({ id: z.string() }),
      body: projectFsCreateEntrySchema,
      responses: {
        201: projectFsCreateEntryResponseSchema,
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Create a file or folder under the project's working directory",
    },
    deleteProjectFsEntry: {
      method: "DELETE",
      path: "/api/v1/projects/:id/fs/entries",
      pathParams: z.object({ id: z.string() }),
      query: z.object({
        path: z.string().min(1).max(4096),
      }),
      body: null,
      responses: {
        200: projectFsDeleteEntryResponseSchema,
        400: errorSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Delete a file or folder under the project's working directory",
    },
    listTasks: {
      method: "GET",
      path: "/api/v1/tasks",
      query: z.object({
        projectId: z.string().optional(),
        contactId: z.string().optional(),
        assigneeId: z.string().optional(),
        status: z.string().optional(),
        inbox: z.coerce.boolean().optional(),
      }),
      responses: {
        200: z.object({ tasks: z.array(taskSchema) }),
        401: errorSchema,
        403: errorSchema,
      },
      summary: "List tasks",
    },
    getTask: {
      method: "GET",
      path: "/api/v1/tasks/:id",
      pathParams: z.object({ id: z.string() }),
      responses: {
        200: taskSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Get task by id",
    },
    createTask: {
      method: "POST",
      path: "/api/v1/tasks",
      body: createTaskSchema,
      responses: {
        201: taskSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Create task",
    },
    updateTask: {
      method: "PATCH",
      path: "/api/v1/tasks/:id",
      pathParams: z.object({ id: z.string() }),
      body: updateTaskSchema,
      responses: {
        200: taskSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Update task",
    },
    deleteTask: {
      method: "DELETE",
      path: "/api/v1/tasks/:id",
      pathParams: z.object({ id: z.string() }),
      body: null,
      responses: {
        204: c.noBody(),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Soft-delete task",
    },
    createTaskImage: {
      method: "POST",
      path: "/api/v1/tasks/:id/images",
      pathParams: z.object({ id: z.string() }),
      headers: z.object({
        "x-filename": z.string().optional(),
        "content-type": z.string().optional(),
      }),
      body: c.type<ArrayBuffer | Blob>(),
      responses: {
        201: s.taskImageSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Upload an image for embedding in a task description",
    },
    getTaskImage: {
      method: "GET",
      path: "/api/v1/tasks/:id/images/:imageId",
      pathParams: s.taskImageParamsSchema,
      responses: {
        200: c.otherResponse({ contentType: "image/*", body: c.type<Blob>() }),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Download a task description image",
    },
    listApiKeys: {
      method: "GET",
      path: "/api/v1/api-keys",
      responses: {
        200: z.object({ apiKeys: z.array(apiKeySchema) }),
        401: errorSchema,
      },
      summary: "List API keys (Clerk session)",
    },
    createApiKey: {
      method: "POST",
      path: "/api/v1/api-keys",
      body: createApiKeySchema,
      responses: {
        201: createApiKeyResponseSchema,
        400: badRequestSchema,
        401: errorSchema,
      },
      summary: "Create API key (Clerk session; secret shown once)",
    },
    updateApiKey: {
      method: "PATCH",
      path: "/api/v1/api-keys/:id",
      pathParams: z.object({ id: z.string() }),
      body: updateApiKeySchema,
      responses: {
        200: apiKeySchema,
        400: badRequestSchema,
        401: errorSchema,
        404: errorSchema,
      },
      summary: "Rename API key (Clerk session)",
    },
    revokeApiKey: {
      method: "DELETE",
      path: "/api/v1/api-keys/:id",
      pathParams: z.object({ id: z.string() }),
      body: null,
      responses: {
        204: c.noBody(),
        401: errorSchema,
        404: errorSchema,
      },
      summary: "Revoke API key (Clerk session)",
    },
    listDocuments: {
      method: "GET",
      path: "/api/v1/documents",
      query: z.object({
        type: documentTypeSchema.optional(),
        projectId: z.string().optional(),
      }),
      responses: {
        200: z.object({ documents: z.array(documentSchema) }),
        401: errorSchema,
        403: errorSchema,
      },
      summary: "List documents",
    },
    getDocument: {
      method: "GET",
      path: "/api/v1/documents/:id",
      pathParams: z.object({ id: z.string() }),
      responses: {
        200: documentSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Get document metadata",
    },
    createDocument: {
      method: "POST",
      path: "/api/v1/documents",
      body: createDocumentSchema,
      responses: {
        201: documentSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
        503: errorSchema,
      },
      summary: "Create document metadata (optional initial content)",
    },
    updateDocument: {
      method: "PATCH",
      path: "/api/v1/documents/:id",
      pathParams: z.object({ id: z.string() }),
      body: updateDocumentSchema,
      responses: {
        200: documentSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
        503: errorSchema,
      },
      summary: "Update document metadata",
    },
    deleteDocument: {
      method: "DELETE",
      path: "/api/v1/documents/:id",
      pathParams: z.object({ id: z.string() }),
      body: null,
      responses: {
        204: c.noBody(),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Soft-delete document",
    },
    getDocumentContent: {
      method: "GET",
      path: "/api/v1/documents/:id/content",
      pathParams: z.object({ id: z.string() }),
      responses: {
        200: documentContentSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Get document body from object storage",
    },
    updateDocumentContent: {
      method: "PATCH",
      path: "/api/v1/documents/:id/content",
      pathParams: z.object({ id: z.string() }),
      body: updateDocumentContentSchema,
      responses: {
        200: documentContentSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
        409: errorSchema,
        503: errorSchema,
      },
      summary: "Write document body to object storage",
    },
    search: {
      method: "GET",
      path: "/api/v1/search",
      query: z.object({
        q: z.string().min(1).max(500),
        type: documentTypeSchema.optional(),
        projectId: z.string().optional(),
        limit: z.coerce.number().int().min(1).max(50).optional(),
      }),
      responses: {
        200: z.object({ results: z.array(searchResultSchema) }),
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Search documents by title, path, and snippet",
    },
    getProjectRelations: {
      method: "GET",
      path: "/api/v1/projects/:id/relations",
      pathParams: s.idParamsSchema,
      responses: { 200: s.projectRelationsSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get project relations",
    },
    listDueTasks: {
      method: "GET",
      path: "/api/v1/tasks/due",
      query: z.object({ before: z.string().datetime().optional() }),
      responses: { 200: z.object({ tasks: z.array(taskSchema) }), 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "List tasks due before a date",
    },
    listInboxTasks: {
      method: "GET",
      path: "/api/v1/tasks/inbox",
      responses: { 200: z.object({ tasks: z.array(taskSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List inbox tasks",
    },
    getTaskRelations: {
      method: "GET",
      path: "/api/v1/tasks/:id/relations",
      pathParams: s.idParamsSchema,
      responses: { 200: s.taskRelationsSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get task relations",
    },
    listTaskComments: {
      method: "GET",
      path: "/api/v1/tasks/:id/comments",
      pathParams: s.idParamsSchema,
      responses: {
        200: z.object({ comments: z.array(taskCommentSchema) }),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "List comments on a task",
    },
    listTaskActivities: {
      method: "GET",
      path: "/api/v1/tasks/:id/activities",
      pathParams: s.idParamsSchema,
      responses: {
        200: z.object({ activities: z.array(taskActivitySchema) }),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "List system activity events on a task (status changes, etc.)",
    },
    createTaskActivity: {
      method: "POST",
      path: "/api/v1/tasks/:id/activities",
      pathParams: s.idParamsSchema,
      body: createTaskActivitySchema,
      responses: {
        201: taskActivitySchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Record a client-reported activity event (e.g. agent turn)",
    },
    createTaskComment: {
      method: "POST",
      path: "/api/v1/tasks/:id/comments",
      pathParams: s.idParamsSchema,
      body: createTaskCommentSchema,
      responses: {
        201: taskCommentSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Create a comment on a task",
    },
    updateTaskComment: {
      method: "PATCH",
      path: "/api/v1/tasks/:taskId/comments/:id",
      pathParams: z.object({ taskId: z.string(), id: z.string() }),
      body: updateTaskCommentSchema,
      responses: {
        200: taskCommentSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Update a task comment",
    },
    deleteTaskComment: {
      method: "DELETE",
      path: "/api/v1/tasks/:taskId/comments/:id",
      pathParams: z.object({ taskId: z.string(), id: z.string() }),
      body: c.noBody(),
      responses: {
        204: c.noBody(),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Soft-delete a task comment",
    },
    batchUpdateTasks: {
      method: "POST",
      path: "/api/v1/tasks/batch",
      body: s.batchUpdateTasksSchema,
      responses: { 200: z.object({ tasks: z.array(taskSchema) }), 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Batch update tasks",
    },
    reorderTasks: {
      method: "POST",
      path: "/api/v1/tasks/reorder",
      body: s.reorderSchema,
      responses: { 200: z.object({ tasks: z.array(taskSchema) }), 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Reorder tasks",
    },
    moveTask: {
      method: "POST",
      path: "/api/v1/tasks/:id/move",
      pathParams: s.idParamsSchema,
      body: s.moveTaskSchema,
      responses: { 200: taskSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Move a task",
    },
    triageTask: {
      method: "POST",
      path: "/api/v1/tasks/:id/triage",
      pathParams: s.idParamsSchema,
      body: s.triageTaskSchema,
      responses: { 200: taskSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Triage a task",
    },
    getJournal: {
      method: "GET",
      path: "/api/v1/journal/:date",
      pathParams: z.object({ date: z.string().date() }),
      responses: { 200: documentSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get or create a journal document",
    },
    getWhoopDay: {
      method: "GET",
      path: "/api/v1/whoop/day",
      query: z.object({ date: z.string().date() }),
      responses: {
        200: whoopDayResultSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Fetch Whoop sleep, recovery, and strain for a calendar day",
    },
    getWhoopStatus: {
      method: "GET",
      path: "/api/v1/whoop/status",
      responses: {
        200: whoopSettingsStatusSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Whoop connection status from local totem.env",
    },
    reorderDocuments: {
      method: "POST",
      path: "/api/v1/documents/reorder",
      body: s.reorderSchema,
      responses: { 200: z.object({ documents: z.array(documentSchema) }), 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Reorder documents and folders",
    },
    moveDocument: {
      method: "POST",
      path: "/api/v1/documents/:id/move",
      pathParams: s.idParamsSchema,
      body: z.object({ parentId: z.string().nullable() }),
      responses: { 200: documentSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Move a document or folder",
    },
    listOrganizations: {
      method: "GET",
      path: "/api/v1/organizations",
      responses: { 200: z.object({ organizations: z.array(s.organizationSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List organizations",
    },
    getOrganization: {
      method: "GET",
      path: "/api/v1/organizations/:id",
      pathParams: s.idParamsSchema,
      responses: { 200: s.organizationSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get an organization",
    },
    getOrganizationRelations: {
      method: "GET",
      path: "/api/v1/organizations/:id/relations",
      pathParams: s.idParamsSchema,
      responses: { 200: s.organizationRelationsSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get organization relations",
    },
    createOrganization: {
      method: "POST",
      path: "/api/v1/organizations",
      body: s.organizationInputSchema,
      responses: { 201: s.organizationSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Create an organization",
    },
    updateOrganization: {
      method: "PATCH",
      path: "/api/v1/organizations/:id",
      pathParams: s.idParamsSchema,
      body: s.updateOrganizationSchema,
      responses: { 200: s.organizationSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Update an organization",
    },
    deleteOrganization: {
      method: "DELETE",
      path: "/api/v1/organizations/:id",
      pathParams: s.idParamsSchema,
      body: null,
      responses: { 204: c.noBody(), 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Delete an organization",
    },
    listContacts: {
      method: "GET",
      path: "/api/v1/contacts",
      query: z.object({ organizationId: z.string().optional(), q: z.string().optional() }),
      responses: { 200: z.object({ contacts: z.array(s.contactSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List contacts",
    },
    getContact: {
      method: "GET",
      path: "/api/v1/contacts/:id",
      pathParams: s.idParamsSchema,
      responses: { 200: s.contactSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get a contact",
    },
    getContactRelations: {
      method: "GET",
      path: "/api/v1/contacts/:id/relations",
      pathParams: s.idParamsSchema,
      responses: { 200: s.contactRelationsSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get contact relations",
    },
    createContact: {
      method: "POST",
      path: "/api/v1/contacts",
      body: s.contactInputSchema,
      responses: { 201: s.contactSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Create a contact",
    },
    updateContact: {
      method: "PATCH",
      path: "/api/v1/contacts/:id",
      pathParams: s.idParamsSchema,
      body: s.updateContactSchema,
      responses: { 200: s.contactSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Update a contact",
    },
    deleteContact: {
      method: "DELETE",
      path: "/api/v1/contacts/:id",
      pathParams: s.idParamsSchema,
      body: null,
      responses: { 204: c.noBody(), 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Delete a contact",
    },
    listAreas: {
      method: "GET",
      path: "/api/v1/areas",
      responses: { 200: z.object({ areas: z.array(s.areaSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List areas",
    },
    getArea: {
      method: "GET",
      path: "/api/v1/areas/:id",
      pathParams: s.idParamsSchema,
      responses: { 200: s.areaSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get an area",
    },
    createArea: {
      method: "POST",
      path: "/api/v1/areas",
      body: s.areaInputSchema,
      responses: { 201: s.areaSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Create an area",
    },
    updateArea: {
      method: "PATCH",
      path: "/api/v1/areas/:id",
      pathParams: s.idParamsSchema,
      body: s.updateAreaSchema,
      responses: { 200: s.areaSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Update an area",
    },
    deleteArea: {
      method: "DELETE",
      path: "/api/v1/areas/:id",
      pathParams: s.idParamsSchema,
      body: null,
      responses: { 204: c.noBody(), 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Delete an area",
    },
    listLetters: {
      method: "GET",
      path: "/api/v1/letters",
      query: z.object({
        projectId: z.string().optional(),
        organizationId: z.string().optional(),
        contactId: z.string().optional(),
        status: z.string().optional(),
        triage: z.coerce.boolean().optional(),
      }),
      responses: { 200: z.object({ letters: z.array(s.letterSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List letters",
    },
    listLetterInbox: {
      method: "GET",
      path: "/api/v1/letters/inbox",
      responses: { 200: z.object({ letters: z.array(s.letterSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List letter inbox",
    },
    getLetter: {
      method: "GET",
      path: "/api/v1/letters/:id",
      pathParams: s.idParamsSchema,
      responses: { 200: s.letterSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get a letter",
    },
    getLetterRelations: {
      method: "GET",
      path: "/api/v1/letters/:id/relations",
      pathParams: s.idParamsSchema,
      responses: { 200: s.letterRelationsSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Get letter relations",
    },
    createLetter: {
      method: "POST",
      path: "/api/v1/letters",
      body: s.letterInputSchema,
      responses: { 201: s.letterSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Create a letter",
    },
    updateLetter: {
      method: "PATCH",
      path: "/api/v1/letters/:id",
      pathParams: s.idParamsSchema,
      body: s.updateLetterSchema,
      responses: { 200: s.letterSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Update a letter",
    },
    deleteLetter: {
      method: "DELETE",
      path: "/api/v1/letters/:id",
      pathParams: s.idParamsSchema,
      body: null,
      responses: { 204: c.noBody(), 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Delete a letter",
    },
    triageLetter: {
      method: "POST",
      path: "/api/v1/letters/:id/triage",
      pathParams: s.idParamsSchema,
      body: s.triageLetterSchema,
      responses: { 200: s.letterSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Triage a letter",
    },
    putLetterPdf: {
      method: "PUT",
      path: "/api/v1/letters/:id/pdf",
      pathParams: s.idParamsSchema,
      headers: z.object({ "x-filename": z.string().optional() }),
      body: c.type<ArrayBuffer | Blob>(),
      responses: { 200: s.letterSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Upload letter PDF (adds an attachment)",
    },
    getLetterPdf: {
      method: "GET",
      path: "/api/v1/letters/:id/pdf",
      pathParams: s.idParamsSchema,
      responses: {
        200: c.otherResponse({ contentType: "application/pdf", body: c.type<Blob>() }),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Download primary letter PDF",
    },
    listLetterAttachments: {
      method: "GET",
      path: "/api/v1/letters/:id/attachments",
      pathParams: s.idParamsSchema,
      responses: {
        200: s.letterAttachmentsResponseSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "List letter PDF attachments",
    },
    createLetterAttachment: {
      method: "POST",
      path: "/api/v1/letters/:id/attachments",
      pathParams: s.idParamsSchema,
      headers: z.object({ "x-filename": z.string().optional() }),
      body: c.type<ArrayBuffer | Blob>(),
      responses: {
        201: s.letterAttachmentSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Add a letter PDF attachment",
    },
    reorderLetterAttachments: {
      method: "POST",
      path: "/api/v1/letters/:id/attachments/reorder",
      pathParams: s.idParamsSchema,
      body: s.reorderLetterAttachmentsSchema,
      responses: {
        200: s.letterAttachmentsResponseSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Reorder letter PDF attachments",
    },
    getLetterAttachment: {
      method: "GET",
      path: "/api/v1/letters/:id/attachments/:attachmentId",
      pathParams: s.letterAttachmentParamsSchema,
      responses: {
        200: c.otherResponse({ contentType: "application/pdf", body: c.type<Blob>() }),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Download a letter PDF attachment",
    },
    updateLetterAttachment: {
      method: "PATCH",
      path: "/api/v1/letters/:id/attachments/:attachmentId",
      pathParams: s.letterAttachmentParamsSchema,
      body: s.updateLetterAttachmentSchema,
      responses: {
        200: s.letterAttachmentSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Rename a letter PDF attachment",
    },
    deleteLetterAttachment: {
      method: "DELETE",
      path: "/api/v1/letters/:id/attachments/:attachmentId",
      pathParams: s.letterAttachmentParamsSchema,
      responses: {
        200: s.letterAttachmentSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Delete a letter PDF attachment",
    },
    putAvatar: {
      method: "PUT",
      path: "/api/v1/avatars/:entityType/:entityId",
      pathParams: s.avatarParamsSchema,
      body: c.type<ArrayBuffer | Blob>(),
      responses: { 200: s.avatarSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Upload avatar",
    },
    getAvatar: {
      method: "GET",
      path: "/api/v1/avatars/:entityType/:entityId",
      pathParams: s.avatarParamsSchema,
      responses: {
        200: c.otherResponse({ contentType: "image/*", body: c.type<Blob>() }),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Download avatar",
    },
    deleteAvatar: {
      method: "DELETE",
      path: "/api/v1/avatars/:entityType/:entityId",
      pathParams: s.avatarParamsSchema,
      responses: {
        200: s.avatarSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Delete avatar",
    },
    getSettings: {
      method: "GET",
      path: "/api/v1/settings",
      responses: { 200: s.settingsResponseSchema, 401: errorSchema, 403: errorSchema },
      summary: "Get workspace settings",
    },
    updateSettings: {
      method: "PATCH",
      path: "/api/v1/settings",
      body: s.settingsSchema,
      responses: { 200: s.settingsResponseSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Update workspace settings",
    },
    getVaultStorageSettings: {
      method: "GET",
      path: "/api/v1/settings/storage",
      responses: {
        200: s.vaultStorageSettingsSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Get local Obsidian-style vault path status",
    },
    updateVaultStorageSettings: {
      method: "PATCH",
      path: "/api/v1/settings/storage",
      body: s.updateVaultStorageSettingsSchema,
      responses: {
        200: s.vaultStorageSettingsSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Set local vault folder path (creates Journal/Projects/Letters/Knowledge Base)",
    },
    getCursorSettings: {
      method: "GET",
      path: "/api/v1/settings/cursor",
      responses: {
        200: s.cursorSettingsSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Get Cursor integration settings (API key redacted)",
    },
    updateCursorSettings: {
      method: "PATCH",
      path: "/api/v1/settings/cursor",
      body: s.updateCursorSettingsSchema,
      responses: {
        200: s.cursorSettingsSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Update Cursor API key and spellcheck preferences",
    },
    listCursorModels: {
      method: "GET",
      path: "/api/v1/settings/cursor/models",
      responses: {
        200: s.cursorModelsResponseSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "List Cursor models available for the stored API key",
    },
    getAgentPtyConnection: {
      method: "GET",
      path: "/api/v1/agent-pty/connection",
      responses: {
        200: s.agentPtyConnectionSchema,
        401: errorSchema,
        403: errorSchema,
        503: errorSchema,
      },
      summary:
        "Discover Tailscale-reachable PTY sidecar URL + auth token for agent TUI clients",
    },
    spellcheck: {
      method: "POST",
      path: "/api/v1/ai/spellcheck",
      body: s.spellcheckRequestSchema,
      responses: {
        200: s.spellcheckResponseSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Fix spelling and light formatting for task title/description",
    },
    research: {
      method: "POST",
      path: "/api/v1/ai/research",
      body: s.researchRequestSchema,
      responses: {
        200: s.researchResponseSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Research a task topic and rewrite title/description with findings",
    },
    listMentions: {
      method: "GET",
      path: "/api/v1/mentions",
      responses: { 200: z.object({ mentions: z.array(s.mentionSchema) }), 401: errorSchema, 403: errorSchema },
      summary: "List mentions",
    },
    createMention: {
      method: "POST",
      path: "/api/v1/mentions",
      body: s.createMentionSchema,
      responses: { 201: s.mentionSchema, 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Create a mention",
    },
    markMentionRead: {
      method: "POST",
      path: "/api/v1/mentions/:id/read",
      pathParams: s.idParamsSchema,
      body: null,
      responses: { 200: s.mentionSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema },
      summary: "Mark mention read",
    },
    globalSearch: {
      method: "GET",
      path: "/api/v1/global-search",
      query: z.object({ q: z.string().min(1), limit: z.coerce.number().int().min(1).max(100).optional() }),
      responses: { 200: z.object({ results: z.array(s.globalSearchResultSchema) }), 400: badRequestSchema, 401: errorSchema, 403: errorSchema },
      summary: "Search all human-facing entities",
    },
    syncBootstrap: {
      method: "POST",
      path: "/api/v1/sync/bootstrap",
      body: null,
      responses: { 200: s.syncBootstrapSchema, 401: errorSchema },
      summary: "Bootstrap legacy sync",
    },
    syncPull: {
      method: "GET",
      path: "/api/v1/sync/pull",
      query: z.object({ cursor: z.coerce.number().int().nonnegative().optional() }),
      responses: { 200: s.syncPullSchema, 400: badRequestSchema, 401: errorSchema },
      summary: "Pull legacy sync events",
    },
    syncPush: {
      method: "POST",
      path: "/api/v1/sync/push",
      body: s.syncPushSchema,
      responses: { 200: s.syncPushResponseSchema, 400: badRequestSchema, 401: errorSchema, 404: errorSchema },
      summary: "Push legacy sync mutations",
    },
    getPowerSyncCredentials: {
      method: "GET",
      path: "/api/v1/powersync/token",
      responses: { 200: s.powerSyncCredentialsSchema, 401: errorSchema, 503: errorSchema },
      summary: "Get short-lived PowerSync credentials",
    },
    powerSyncWrite: {
      method: "POST",
      path: "/api/v1/powersync/write",
      body: s.powerSyncWriteSchema,
      responses: { 200: s.okSchema, 400: badRequestSchema, 401: errorSchema, 404: errorSchema },
      summary: "Apply a PowerSync write batch",
    },
    opsSyncHealth: {
      method: "GET",
      path: "/api/v1/ops/sync-health",
      responses: {
        200: s.opsSyncHealthSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Owner ops: sync cursor + recent devices",
    },
    opsLogs: {
      method: "GET",
      path: "/api/v1/ops/logs",
      query: z.object({
        limit: z.coerce.number().int().min(1).max(200).optional(),
      }),
      responses: {
        200: s.opsLogsSchema,
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Owner ops: recent process log tail",
    },
    listRecurringTasks: {
      method: "GET",
      path: "/api/v1/ops/recurring-tasks",
      responses: {
        200: z.object({ recurringTasks: z.array(s.recurringTaskSchema) }),
        401: errorSchema,
        403: errorSchema,
      },
      summary: "Owner ops: list recurring task templates",
    },
    createRecurringTask: {
      method: "POST",
      path: "/api/v1/ops/recurring-tasks",
      body: s.createRecurringTaskSchema,
      responses: {
        201: s.recurringTaskSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Owner ops: create a recurring task template",
    },
    updateRecurringTask: {
      method: "PATCH",
      path: "/api/v1/ops/recurring-tasks/:id",
      pathParams: z.object({ id: z.string() }),
      body: s.updateRecurringTaskSchema,
      responses: {
        200: s.recurringTaskSchema,
        400: badRequestSchema,
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Owner ops: update a recurring task template",
    },
    deleteRecurringTask: {
      method: "DELETE",
      path: "/api/v1/ops/recurring-tasks/:id",
      pathParams: z.object({ id: z.string() }),
      responses: {
        204: z.void(),
        401: errorSchema,
        403: errorSchema,
        404: errorSchema,
      },
      summary: "Owner ops: soft-delete a recurring task template",
    },
  },
  {
    pathPrefix: "",
  },
);

export type ApiContract = typeof apiContract;
