"use client";

import type { ComponentType, SVGProps } from "react";
import {
  AccessibilityIcon,
  AccessibilityInsetIcon,
  AgentIcon,
  AiModelIcon,
  AlertIcon,
  AlertFillIcon,
  AppsIcon,
  ArchiveIcon,
  ArrowBothIcon,
  ArrowDownIcon,
  ArrowDownLeftIcon,
  ArrowDownRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSwitchIcon,
  ArrowUpIcon,
  ArrowUpLeftIcon,
  ArrowUpRightIcon,
  BeakerIcon,
  BellIcon,
  BellFillIcon,
  BellSlashIcon,
  BlockedIcon,
  BoldIcon,
  BookIcon,
  BookLockedIcon,
  BookmarkIcon,
  BookmarkFillIcon,
  BookmarkFilledIcon,
  BookmarkSlashIcon,
  BookmarkSlashFillIcon,
  BooleanOffIcon,
  BooleanOnIcon,
  BriefcaseIcon,
  BroadcastIcon,
  BrowserIcon,
  BugIcon,
  CacheIcon,
  CalendarIcon,
  CheckIcon,
  CheckCircleIcon,
  CheckCircleFillIcon,
  CheckboxIcon,
  CheckboxFillIcon,
  ChecklistIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleIcon,
  CircleSlashIcon,
  ClockIcon,
  ClockFillIcon,
  CloudIcon,
  CloudOfflineIcon,
  CodeIcon,
  CodeOfConductIcon,
  CodeReviewIcon,
  CodeSquareIcon,
  CodescanIcon,
  CodescanCheckmarkIcon,
  CodespacesIcon,
  ColumnsIcon,
  CommandPaletteIcon,
  CommentIcon,
  CommentAiIcon,
  CommentDiscussionIcon,
  CommentLockedIcon,
  ComposeIcon,
  ContainerIcon,
  CopilotIcon,
  CopilotErrorIcon,
  CopilotWarningIcon,
  CopyIcon,
  CpuIcon,
  CreditCardIcon,
  CrossReferenceIcon,
  CrosshairsIcon,
  DashIcon,
  DatabaseIcon,
  DependabotIcon,
  DesktopDownloadIcon,
  DeviceCameraIcon,
  DeviceCameraVideoIcon,
  DeviceDesktopIcon,
  DeviceMobileIcon,
  DevicesIcon,
  DiamondIcon,
  DiceIcon,
  DiffIcon,
  DiffAddedIcon,
  DiffIgnoredIcon,
  DiffModifiedIcon,
  DiffRemovedIcon,
  DiffRenamedIcon,
  DiscussionClosedIcon,
  DiscussionDuplicateIcon,
  DiscussionOutdatedIcon,
  DotIcon,
  DotFillIcon,
  DownloadIcon,
  DuplicateIcon,
  EllipsisIcon,
  ExclamationIcon,
  EyeIcon,
  EyeClosedIcon,
  FeedDiscussionIcon,
  FeedForkedIcon,
  FeedHeartIcon,
  FeedIssueClosedIcon,
  FeedIssueDraftIcon,
  FeedIssueOpenIcon,
  FeedIssueReopenIcon,
  FeedMergedIcon,
  FeedPersonIcon,
  FeedPlusIcon,
  FeedPublicIcon,
  FeedPullRequestClosedIcon,
  FeedPullRequestDraftIcon,
  FeedPullRequestOpenIcon,
  FeedRepoIcon,
  FeedRocketIcon,
  FeedStarIcon,
  FeedTagIcon,
  FeedTrophyIcon,
  FileIcon,
  FileAddedIcon,
  FileBadgeIcon,
  FileBinaryIcon,
  FileCheckIcon,
  FileCodeIcon,
  FileDiffIcon,
  FileDirectoryIcon,
  FileDirectoryFillIcon,
  FileDirectoryOpenFillIcon,
  FileDirectorySymlinkIcon,
  FileMediaIcon,
  FileMovedIcon,
  FileRemovedIcon,
  FileSubmoduleIcon,
  FileSymlinkFileIcon,
  FileZipIcon,
  FilterIcon,
  FilterRemoveIcon,
  FiscalHostIcon,
  FlagIcon,
  FlameIcon,
  FlowchartIcon,
  FocusCenterIcon,
  FoldIcon,
  FoldDownIcon,
  FoldUpIcon,
  GearIcon,
  GiftIcon,
  GitBranchIcon,
  GitBranchCheckIcon,
  GitCommitIcon,
  GitCompareIcon,
  GitMergeIcon,
  GitMergeQueueIcon,
  GitPullRequestIcon,
  GitPullRequestClosedIcon,
  GitPullRequestDraftIcon,
  GitPullRequestLockedIcon,
  GlobeIcon,
  GoalIcon,
  GrabberIcon,
  GraphIcon,
  GraphBarHorizontalIcon,
  GraphBarVerticalIcon,
  GraphStackedAreaIcon,
  HashIcon,
  HeadingIcon,
  HeartIcon,
  HeartFillIcon,
  HistoryIcon,
  HomeIcon,
  HomeFillIcon,
  HorizontalRuleIcon,
  HourglassIcon,
  HubotIcon,
  IdBadgeIcon,
  ImageIcon,
  InboxIcon,
  InboxFillIcon,
  InfinityIcon,
  InfoIcon,
  IssueClosedIcon,
  IssueDraftIcon,
  IssueLockedIcon,
  IssueOpenedIcon,
  IssueReopenedIcon,
  IssueTrackedByIcon,
  IssueTracksIcon,
  ItalicIcon,
  IterationsIcon,
  KebabHorizontalIcon,
  KeyIcon,
  KeyAsteriskIcon,
  LawIcon,
  LightBulbIcon,
  LinkIcon,
  LinkExternalIcon,
  ListOrderedIcon,
  ListUnorderedIcon,
  LocationIcon,
  LockIcon,
  LockupGithubIcon,
  LogIcon,
  LogoGistIcon,
  LogoGithubIcon,
  LoopIcon,
  MailIcon,
  MarkGithubIcon,
  MarkdownIcon,
  MaximizeIcon,
  McpIcon,
  MegaphoneIcon,
  MentionIcon,
  MeterIcon,
  MilestoneIcon,
  MinimizeIcon,
  MirrorIcon,
  MoonIcon,
  MortarBoardIcon,
  MoveToBottomIcon,
  MoveToEndIcon,
  MoveToStartIcon,
  MoveToTopIcon,
  MultiSelectIcon,
  MuteIcon,
  NoEntryIcon,
  NoEntryFillIcon,
  NodeIcon,
  NorthStarIcon,
  NoteIcon,
  NumberIcon,
  OrganizationIcon,
  PackageIcon,
  PackageDependenciesIcon,
  PackageDependentsIcon,
  PaintbrushIcon,
  PaperAirplaneIcon,
  PaperclipIcon,
  PasskeyFillIcon,
  PasteIcon,
  PauseIcon,
  PencilIcon,
  PencilAiIcon,
  PeopleIcon,
  PersonIcon,
  PersonAddIcon,
  PersonFillIcon,
  PinIcon,
  PinSlashIcon,
  PivotColumnIcon,
  PlayIcon,
  PlugIcon,
  PlusIcon,
  PlusCircleIcon,
  ProjectIcon,
  ProjectCheckIcon,
  ProjectRoadmapIcon,
  ProjectSymlinkIcon,
  ProjectTemplateIcon,
  PulseIcon,
  QuestionIcon,
  QuoteIcon,
  ReadIcon,
  RedoIcon,
  RelFilePathIcon,
  ReplyIcon,
  RepoIcon,
  RepoCloneIcon,
  RepoDeleteIcon,
  RepoDeletedIcon,
  RepoForkedIcon,
  RepoForkedLockedIcon,
  RepoLockedIcon,
  RepoPullIcon,
  RepoPushIcon,
  RepoTemplateIcon,
  ReportIcon,
  RocketIcon,
  RowsIcon,
  RssIcon,
  RubyIcon,
  SandboxIcon,
  ScreenFullIcon,
  ScreenNormalIcon,
  SearchIcon,
  ServerIcon,
  ShareIcon,
  ShareAndroidIcon,
  ShieldIcon,
  ShieldCheckIcon,
  ShieldLockIcon,
  ShieldSlashIcon,
  ShieldXIcon,
  SidebarCollapseIcon,
  SidebarExpandIcon,
  SignInIcon,
  SignOutIcon,
  SingleSelectIcon,
  SkipIcon,
  SkipFillIcon,
  SlidersIcon,
  SmileyIcon,
  SmileyFrownIcon,
  SmileyFrustratedIcon,
  SmileyGrinIcon,
  SmileyNeutralIcon,
  SortAscIcon,
  SortDescIcon,
  SpaceIcon,
  SpacingLargeIcon,
  SpacingMediumIcon,
  SpacingSmallIcon,
  SparkleIcon,
  SparkleFillIcon,
  SparklesFillIcon,
  SplitViewIcon,
  SponsorTiersIcon,
  SquareIcon,
  SquareCircleIcon,
  SquareFillIcon,
  SquirrelIcon,
  StackIcon,
  StackAddIcon,
  StackCheckIcon,
  StackRemoveIcon,
  StarIcon,
  StarFillIcon,
  StopIcon,
  StopwatchIcon,
  StrikethroughIcon,
  SunIcon,
  SyncIcon,
  TabIcon,
  TabExternalIcon,
  TableIcon,
  TagIcon,
  TasklistIcon,
  TelescopeIcon,
  TelescopeFillIcon,
  TerminalIcon,
  ThreeBarsIcon,
  ThumbsdownIcon,
  ThumbsupIcon,
  ToolsIcon,
  TrackedByClosedCompletedIcon,
  TrackedByClosedNotPlannedIcon,
  TrashIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleUpIcon,
  TrophyIcon,
  TypographyIcon,
  UndoIcon,
  UnfoldIcon,
  UnlinkIcon,
  UnlockIcon,
  UnmuteIcon,
  UnreadIcon,
  UnverifiedIcon,
  UnwrapIcon,
  UploadIcon,
  VerifiedIcon,
  VersionsIcon,
  VideoIcon,
  ViewFilesIcon,
  VscodeIcon,
  WebhookIcon,
  WorkflowIcon,
  WrapIcon,
  XIcon,
  XCircleIcon,
  XCircleFillIcon,
  ZapIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "@primer/octicons-react";

import type { ProjectIconKey } from "@/lib/project-icon-keys";

export type ProjectOcticonProps = SVGProps<SVGSVGElement> & {
  size?: number | string;
};

const OCTICON_BY_KEY = {
  "accessibility": AccessibilityIcon,
  "accessibility-inset": AccessibilityInsetIcon,
  "agent": AgentIcon,
  "ai-model": AiModelIcon,
  "alert": AlertIcon,
  "alert-fill": AlertFillIcon,
  "apps": AppsIcon,
  "archive": ArchiveIcon,
  "arrow-both": ArrowBothIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-down-left": ArrowDownLeftIcon,
  "arrow-down-right": ArrowDownRightIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-switch": ArrowSwitchIcon,
  "arrow-up": ArrowUpIcon,
  "arrow-up-left": ArrowUpLeftIcon,
  "arrow-up-right": ArrowUpRightIcon,
  "beaker": BeakerIcon,
  "bell": BellIcon,
  "bell-fill": BellFillIcon,
  "bell-slash": BellSlashIcon,
  "blocked": BlockedIcon,
  "bold": BoldIcon,
  "book": BookIcon,
  "book-locked": BookLockedIcon,
  "bookmark": BookmarkIcon,
  "bookmark-fill": BookmarkFillIcon,
  "bookmark-filled": BookmarkFilledIcon,
  "bookmark-slash": BookmarkSlashIcon,
  "bookmark-slash-fill": BookmarkSlashFillIcon,
  "boolean-off": BooleanOffIcon,
  "boolean-on": BooleanOnIcon,
  "briefcase": BriefcaseIcon,
  "broadcast": BroadcastIcon,
  "browser": BrowserIcon,
  "bug": BugIcon,
  "cache": CacheIcon,
  "calendar": CalendarIcon,
  "check": CheckIcon,
  "check-circle": CheckCircleIcon,
  "check-circle-fill": CheckCircleFillIcon,
  "checkbox": CheckboxIcon,
  "checkbox-fill": CheckboxFillIcon,
  "checklist": ChecklistIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  "circle": CircleIcon,
  "circle-slash": CircleSlashIcon,
  "clock": ClockIcon,
  "clock-fill": ClockFillIcon,
  "cloud": CloudIcon,
  "cloud-offline": CloudOfflineIcon,
  "code": CodeIcon,
  "code-of-conduct": CodeOfConductIcon,
  "code-review": CodeReviewIcon,
  "code-square": CodeSquareIcon,
  "codescan": CodescanIcon,
  "codescan-checkmark": CodescanCheckmarkIcon,
  "codespaces": CodespacesIcon,
  "columns": ColumnsIcon,
  "command-palette": CommandPaletteIcon,
  "comment": CommentIcon,
  "comment-ai": CommentAiIcon,
  "comment-discussion": CommentDiscussionIcon,
  "comment-locked": CommentLockedIcon,
  "compose": ComposeIcon,
  "container": ContainerIcon,
  "copilot": CopilotIcon,
  "copilot-error": CopilotErrorIcon,
  "copilot-warning": CopilotWarningIcon,
  "copy": CopyIcon,
  "cpu": CpuIcon,
  "credit-card": CreditCardIcon,
  "cross-reference": CrossReferenceIcon,
  "crosshairs": CrosshairsIcon,
  "dash": DashIcon,
  "database": DatabaseIcon,
  "dependabot": DependabotIcon,
  "desktop-download": DesktopDownloadIcon,
  "device-camera": DeviceCameraIcon,
  "device-camera-video": DeviceCameraVideoIcon,
  "device-desktop": DeviceDesktopIcon,
  "device-mobile": DeviceMobileIcon,
  "devices": DevicesIcon,
  "diamond": DiamondIcon,
  "dice": DiceIcon,
  "diff": DiffIcon,
  "diff-added": DiffAddedIcon,
  "diff-ignored": DiffIgnoredIcon,
  "diff-modified": DiffModifiedIcon,
  "diff-removed": DiffRemovedIcon,
  "diff-renamed": DiffRenamedIcon,
  "discussion-closed": DiscussionClosedIcon,
  "discussion-duplicate": DiscussionDuplicateIcon,
  "discussion-outdated": DiscussionOutdatedIcon,
  "dot": DotIcon,
  "dot-fill": DotFillIcon,
  "download": DownloadIcon,
  "duplicate": DuplicateIcon,
  "ellipsis": EllipsisIcon,
  "exclamation": ExclamationIcon,
  "eye": EyeIcon,
  "eye-closed": EyeClosedIcon,
  "feed-discussion": FeedDiscussionIcon,
  "feed-forked": FeedForkedIcon,
  "feed-heart": FeedHeartIcon,
  "feed-issue-closed": FeedIssueClosedIcon,
  "feed-issue-draft": FeedIssueDraftIcon,
  "feed-issue-open": FeedIssueOpenIcon,
  "feed-issue-reopen": FeedIssueReopenIcon,
  "feed-merged": FeedMergedIcon,
  "feed-person": FeedPersonIcon,
  "feed-plus": FeedPlusIcon,
  "feed-public": FeedPublicIcon,
  "feed-pull-request-closed": FeedPullRequestClosedIcon,
  "feed-pull-request-draft": FeedPullRequestDraftIcon,
  "feed-pull-request-open": FeedPullRequestOpenIcon,
  "feed-repo": FeedRepoIcon,
  "feed-rocket": FeedRocketIcon,
  "feed-star": FeedStarIcon,
  "feed-tag": FeedTagIcon,
  "feed-trophy": FeedTrophyIcon,
  "file": FileIcon,
  "file-added": FileAddedIcon,
  "file-badge": FileBadgeIcon,
  "file-binary": FileBinaryIcon,
  "file-check": FileCheckIcon,
  "file-code": FileCodeIcon,
  "file-diff": FileDiffIcon,
  "file-directory": FileDirectoryIcon,
  "file-directory-fill": FileDirectoryFillIcon,
  "file-directory-open-fill": FileDirectoryOpenFillIcon,
  "file-directory-symlink": FileDirectorySymlinkIcon,
  "file-media": FileMediaIcon,
  "file-moved": FileMovedIcon,
  "file-removed": FileRemovedIcon,
  "file-submodule": FileSubmoduleIcon,
  "file-symlink-file": FileSymlinkFileIcon,
  "file-zip": FileZipIcon,
  "filter": FilterIcon,
  "filter-remove": FilterRemoveIcon,
  "fiscal-host": FiscalHostIcon,
  "flag": FlagIcon,
  "flame": FlameIcon,
  "flowchart": FlowchartIcon,
  "focus-center": FocusCenterIcon,
  "fold": FoldIcon,
  "fold-down": FoldDownIcon,
  "fold-up": FoldUpIcon,
  "gear": GearIcon,
  "gift": GiftIcon,
  "git-branch": GitBranchIcon,
  "git-branch-check": GitBranchCheckIcon,
  "git-commit": GitCommitIcon,
  "git-compare": GitCompareIcon,
  "git-merge": GitMergeIcon,
  "git-merge-queue": GitMergeQueueIcon,
  "git-pull-request": GitPullRequestIcon,
  "git-pull-request-closed": GitPullRequestClosedIcon,
  "git-pull-request-draft": GitPullRequestDraftIcon,
  "git-pull-request-locked": GitPullRequestLockedIcon,
  "globe": GlobeIcon,
  "goal": GoalIcon,
  "grabber": GrabberIcon,
  "graph": GraphIcon,
  "graph-bar-horizontal": GraphBarHorizontalIcon,
  "graph-bar-vertical": GraphBarVerticalIcon,
  "graph-stacked-area": GraphStackedAreaIcon,
  "hash": HashIcon,
  "heading": HeadingIcon,
  "heart": HeartIcon,
  "heart-fill": HeartFillIcon,
  "history": HistoryIcon,
  "home": HomeIcon,
  "home-fill": HomeFillIcon,
  "horizontal-rule": HorizontalRuleIcon,
  "hourglass": HourglassIcon,
  "hubot": HubotIcon,
  "id-badge": IdBadgeIcon,
  "image": ImageIcon,
  "inbox": InboxIcon,
  "inbox-fill": InboxFillIcon,
  "infinity": InfinityIcon,
  "info": InfoIcon,
  "issue-closed": IssueClosedIcon,
  "issue-draft": IssueDraftIcon,
  "issue-locked": IssueLockedIcon,
  "issue-opened": IssueOpenedIcon,
  "issue-reopened": IssueReopenedIcon,
  "issue-tracked-by": IssueTrackedByIcon,
  "issue-tracks": IssueTracksIcon,
  "italic": ItalicIcon,
  "iterations": IterationsIcon,
  "kebab-horizontal": KebabHorizontalIcon,
  "key": KeyIcon,
  "key-asterisk": KeyAsteriskIcon,
  "law": LawIcon,
  "light-bulb": LightBulbIcon,
  "link": LinkIcon,
  "link-external": LinkExternalIcon,
  "list-ordered": ListOrderedIcon,
  "list-unordered": ListUnorderedIcon,
  "location": LocationIcon,
  "lock": LockIcon,
  "lockup-github": LockupGithubIcon,
  "log": LogIcon,
  "logo-gist": LogoGistIcon,
  "logo-github": LogoGithubIcon,
  "loop": LoopIcon,
  "mail": MailIcon,
  "mark-github": MarkGithubIcon,
  "markdown": MarkdownIcon,
  "maximize": MaximizeIcon,
  "mcp": McpIcon,
  "megaphone": MegaphoneIcon,
  "mention": MentionIcon,
  "meter": MeterIcon,
  "milestone": MilestoneIcon,
  "minimize": MinimizeIcon,
  "mirror": MirrorIcon,
  "moon": MoonIcon,
  "mortar-board": MortarBoardIcon,
  "move-to-bottom": MoveToBottomIcon,
  "move-to-end": MoveToEndIcon,
  "move-to-start": MoveToStartIcon,
  "move-to-top": MoveToTopIcon,
  "multi-select": MultiSelectIcon,
  "mute": MuteIcon,
  "no-entry": NoEntryIcon,
  "no-entry-fill": NoEntryFillIcon,
  "node": NodeIcon,
  "north-star": NorthStarIcon,
  "note": NoteIcon,
  "number": NumberIcon,
  "organization": OrganizationIcon,
  "package": PackageIcon,
  "package-dependencies": PackageDependenciesIcon,
  "package-dependents": PackageDependentsIcon,
  "paintbrush": PaintbrushIcon,
  "paper-airplane": PaperAirplaneIcon,
  "paperclip": PaperclipIcon,
  "passkey-fill": PasskeyFillIcon,
  "paste": PasteIcon,
  "pause": PauseIcon,
  "pencil": PencilIcon,
  "pencil-ai": PencilAiIcon,
  "people": PeopleIcon,
  "person": PersonIcon,
  "person-add": PersonAddIcon,
  "person-fill": PersonFillIcon,
  "pin": PinIcon,
  "pin-slash": PinSlashIcon,
  "pivot-column": PivotColumnIcon,
  "play": PlayIcon,
  "plug": PlugIcon,
  "plus": PlusIcon,
  "plus-circle": PlusCircleIcon,
  "project": ProjectIcon,
  "project-check": ProjectCheckIcon,
  "project-roadmap": ProjectRoadmapIcon,
  "project-symlink": ProjectSymlinkIcon,
  "project-template": ProjectTemplateIcon,
  "pulse": PulseIcon,
  "question": QuestionIcon,
  "quote": QuoteIcon,
  "read": ReadIcon,
  "redo": RedoIcon,
  "rel-file-path": RelFilePathIcon,
  "reply": ReplyIcon,
  "repo": RepoIcon,
  "repo-clone": RepoCloneIcon,
  "repo-delete": RepoDeleteIcon,
  "repo-deleted": RepoDeletedIcon,
  "repo-forked": RepoForkedIcon,
  "repo-forked-locked": RepoForkedLockedIcon,
  "repo-locked": RepoLockedIcon,
  "repo-pull": RepoPullIcon,
  "repo-push": RepoPushIcon,
  "repo-template": RepoTemplateIcon,
  "report": ReportIcon,
  "rocket": RocketIcon,
  "rows": RowsIcon,
  "rss": RssIcon,
  "ruby": RubyIcon,
  "sandbox": SandboxIcon,
  "screen-full": ScreenFullIcon,
  "screen-normal": ScreenNormalIcon,
  "search": SearchIcon,
  "server": ServerIcon,
  "share": ShareIcon,
  "share-android": ShareAndroidIcon,
  "shield": ShieldIcon,
  "shield-check": ShieldCheckIcon,
  "shield-lock": ShieldLockIcon,
  "shield-slash": ShieldSlashIcon,
  "shield-x": ShieldXIcon,
  "sidebar-collapse": SidebarCollapseIcon,
  "sidebar-expand": SidebarExpandIcon,
  "sign-in": SignInIcon,
  "sign-out": SignOutIcon,
  "single-select": SingleSelectIcon,
  "skip": SkipIcon,
  "skip-fill": SkipFillIcon,
  "sliders": SlidersIcon,
  "smiley": SmileyIcon,
  "smiley-frown": SmileyFrownIcon,
  "smiley-frustrated": SmileyFrustratedIcon,
  "smiley-grin": SmileyGrinIcon,
  "smiley-neutral": SmileyNeutralIcon,
  "sort-asc": SortAscIcon,
  "sort-desc": SortDescIcon,
  "space": SpaceIcon,
  "spacing-large": SpacingLargeIcon,
  "spacing-medium": SpacingMediumIcon,
  "spacing-small": SpacingSmallIcon,
  "sparkle": SparkleIcon,
  "sparkle-fill": SparkleFillIcon,
  "sparkles-fill": SparklesFillIcon,
  "split-view": SplitViewIcon,
  "sponsor-tiers": SponsorTiersIcon,
  "square": SquareIcon,
  "square-circle": SquareCircleIcon,
  "square-fill": SquareFillIcon,
  "squirrel": SquirrelIcon,
  "stack": StackIcon,
  "stack-add": StackAddIcon,
  "stack-check": StackCheckIcon,
  "stack-remove": StackRemoveIcon,
  "star": StarIcon,
  "star-fill": StarFillIcon,
  "stop": StopIcon,
  "stopwatch": StopwatchIcon,
  "strikethrough": StrikethroughIcon,
  "sun": SunIcon,
  "sync": SyncIcon,
  "tab": TabIcon,
  "tab-external": TabExternalIcon,
  "table": TableIcon,
  "tag": TagIcon,
  "tasklist": TasklistIcon,
  "telescope": TelescopeIcon,
  "telescope-fill": TelescopeFillIcon,
  "terminal": TerminalIcon,
  "three-bars": ThreeBarsIcon,
  "thumbsdown": ThumbsdownIcon,
  "thumbsup": ThumbsupIcon,
  "tools": ToolsIcon,
  "tracked-by-closed-completed": TrackedByClosedCompletedIcon,
  "tracked-by-closed-not-planned": TrackedByClosedNotPlannedIcon,
  "trash": TrashIcon,
  "triangle-down": TriangleDownIcon,
  "triangle-left": TriangleLeftIcon,
  "triangle-right": TriangleRightIcon,
  "triangle-up": TriangleUpIcon,
  "trophy": TrophyIcon,
  "typography": TypographyIcon,
  "undo": UndoIcon,
  "unfold": UnfoldIcon,
  "unlink": UnlinkIcon,
  "unlock": UnlockIcon,
  "unmute": UnmuteIcon,
  "unread": UnreadIcon,
  "unverified": UnverifiedIcon,
  "unwrap": UnwrapIcon,
  "upload": UploadIcon,
  "verified": VerifiedIcon,
  "versions": VersionsIcon,
  "video": VideoIcon,
  "view-files": ViewFilesIcon,
  "vscode": VscodeIcon,
  "webhook": WebhookIcon,
  "workflow": WorkflowIcon,
  "wrap": WrapIcon,
  "x": XIcon,
  "x-circle": XCircleIcon,
  "x-circle-fill": XCircleFillIcon,
  "zap": ZapIcon,
  "zoom-in": ZoomInIcon,
  "zoom-out": ZoomOutIcon,
} as Record<ProjectIconKey, ComponentType<ProjectOcticonProps>>;

export function getOcticonComponent(
  key: ProjectIconKey,
): ComponentType<ProjectOcticonProps> | null {
  return OCTICON_BY_KEY[key] ?? null;
}
