export type EntityIconEmojiEntry = {
  emoji: string;
  keywords: string[];
};

/** Curated emoji set for document and letter icons (searchable by keywords). */
export const ENTITY_ICON_EMOJIS: EntityIconEmojiEntry[] = [
  { emoji: "😀", keywords: ["grinning", "face", "happy", "smile"] },
  { emoji: "😃", keywords: ["smiley", "face", "happy"] },
  { emoji: "😄", keywords: ["smile", "face", "happy"] },
  { emoji: "😁", keywords: ["beaming", "grin", "face"] },
  { emoji: "😅", keywords: ["sweat", "smile", "face"] },
  { emoji: "😂", keywords: ["joy", "laugh", "tears", "face"] },
  { emoji: "🤣", keywords: ["rofl", "laugh", "face"] },
  { emoji: "😊", keywords: ["blush", "smile", "face"] },
  { emoji: "😇", keywords: ["innocent", "halo", "face"] },
  { emoji: "🙂", keywords: ["slight", "smile", "face"] },
  { emoji: "😉", keywords: ["wink", "face"] },
  { emoji: "😍", keywords: ["heart", "eyes", "love", "face"] },
  { emoji: "🥰", keywords: ["hearts", "love", "face"] },
  { emoji: "😘", keywords: ["kiss", "face"] },
  { emoji: "😎", keywords: ["cool", "sunglasses", "face"] },
  { emoji: "🤔", keywords: ["thinking", "face"] },
  { emoji: "😐", keywords: ["neutral", "face"] },
  { emoji: "😑", keywords: ["expressionless", "face"] },
  { emoji: "😶", keywords: ["silent", "face"] },
  { emoji: "🙄", keywords: ["roll", "eyes", "face"] },
  { emoji: "😏", keywords: ["smirk", "face"] },
  { emoji: "😣", keywords: ["persevere", "face"] },
  { emoji: "😥", keywords: ["sad", "relieved", "face"] },
  { emoji: "😮", keywords: ["open", "mouth", "face"] },
  { emoji: "😯", keywords: ["hushed", "face"] },
  { emoji: "😲", keywords: ["astonished", "face"] },
  { emoji: "😳", keywords: ["flushed", "face"] },
  { emoji: "🥺", keywords: ["pleading", "face"] },
  { emoji: "😢", keywords: ["cry", "tear", "sad", "face"] },
  { emoji: "😭", keywords: ["sob", "cry", "face"] },
  { emoji: "😤", keywords: ["triumph", "face"] },
  { emoji: "😡", keywords: ["angry", "mad", "face"] },
  { emoji: "🤯", keywords: ["exploding", "mind", "face"] },
  { emoji: "😱", keywords: ["scream", "fear", "face"] },
  { emoji: "🤗", keywords: ["hug", "face"] },
  { emoji: "🤫", keywords: ["shush", "quiet", "face"] },
  { emoji: "🤭", keywords: ["giggle", "face"] },
  { emoji: "🫡", keywords: ["salute", "face"] },
  { emoji: "🤝", keywords: ["handshake", "deal", "agreement"] },
  { emoji: "👍", keywords: ["thumbs", "up", "yes", "good"] },
  { emoji: "👎", keywords: ["thumbs", "down", "no", "bad"] },
  { emoji: "👏", keywords: ["clap", "applause", "hands"] },
  { emoji: "🙌", keywords: ["raise", "hands", "celebrate"] },
  { emoji: "🙏", keywords: ["pray", "thanks", "please", "hands"] },
  { emoji: "💪", keywords: ["muscle", "strong", "flex"] },
  { emoji: "❤️", keywords: ["heart", "red", "love"] },
  { emoji: "🧡", keywords: ["heart", "orange", "love"] },
  { emoji: "💛", keywords: ["heart", "yellow", "love"] },
  { emoji: "💚", keywords: ["heart", "green", "love"] },
  { emoji: "💙", keywords: ["heart", "blue", "love"] },
  { emoji: "💜", keywords: ["heart", "purple", "love"] },
  { emoji: "🖤", keywords: ["heart", "black", "love"] },
  { emoji: "💔", keywords: ["broken", "heart", "sad"] },
  { emoji: "⭐", keywords: ["star", "favorite"] },
  { emoji: "🌟", keywords: ["glowing", "star"] },
  { emoji: "✨", keywords: ["sparkles", "magic", "new"] },
  { emoji: "🔥", keywords: ["fire", "hot", "lit"] },
  { emoji: "💧", keywords: ["droplet", "water"] },
  { emoji: "🌈", keywords: ["rainbow", "pride"] },
  { emoji: "☀️", keywords: ["sun", "sunny", "weather"] },
  { emoji: "🌤️", keywords: ["sun", "cloud", "weather"] },
  { emoji: "⛅", keywords: ["cloud", "sun", "weather"] },
  { emoji: "🌥️", keywords: ["cloud", "weather"] },
  { emoji: "☁️", keywords: ["cloud", "weather"] },
  { emoji: "🌧️", keywords: ["rain", "weather"] },
  { emoji: "⛈️", keywords: ["storm", "lightning", "weather"] },
  { emoji: "❄️", keywords: ["snow", "cold", "weather"] },
  { emoji: "🌊", keywords: ["wave", "ocean", "water"] },
  { emoji: "🌸", keywords: ["cherry", "blossom", "flower"] },
  { emoji: "🌺", keywords: ["hibiscus", "flower"] },
  { emoji: "🌻", keywords: ["sunflower", "flower"] },
  { emoji: "🌹", keywords: ["rose", "flower"] },
  { emoji: "🌿", keywords: ["herb", "leaf", "plant"] },
  { emoji: "🍀", keywords: ["clover", "luck", "plant"] },
  { emoji: "🌳", keywords: ["tree", "nature"] },
  { emoji: "🍎", keywords: ["apple", "fruit", "food"] },
  { emoji: "🍊", keywords: ["orange", "fruit", "food"] },
  { emoji: "🍋", keywords: ["lemon", "fruit", "food"] },
  { emoji: "🍌", keywords: ["banana", "fruit", "food"] },
  { emoji: "🍉", keywords: ["watermelon", "fruit", "food"] },
  { emoji: "🍇", keywords: ["grapes", "fruit", "food"] },
  { emoji: "🍓", keywords: ["strawberry", "fruit", "food"] },
  { emoji: "🫐", keywords: ["blueberry", "fruit", "food"] },
  { emoji: "🍒", keywords: ["cherry", "fruit", "food"] },
  { emoji: "🥑", keywords: ["avocado", "food"] },
  { emoji: "🍔", keywords: ["burger", "food", "fast"] },
  { emoji: "🍕", keywords: ["pizza", "food"] },
  { emoji: "🌮", keywords: ["taco", "food"] },
  { emoji: "🍣", keywords: ["sushi", "food"] },
  { emoji: "🍜", keywords: ["noodles", "ramen", "food"] },
  { emoji: "🍩", keywords: ["donut", "food", "dessert"] },
  { emoji: "🍪", keywords: ["cookie", "food", "dessert"] },
  { emoji: "🎂", keywords: ["cake", "birthday", "dessert"] },
  { emoji: "☕", keywords: ["coffee", "drink", "cafe"] },
  { emoji: "🍵", keywords: ["tea", "drink"] },
  { emoji: "🍺", keywords: ["beer", "drink"] },
  { emoji: "🍷", keywords: ["wine", "drink"] },
  { emoji: "⚽", keywords: ["soccer", "football", "sport"] },
  { emoji: "🏀", keywords: ["basketball", "sport"] },
  { emoji: "🏈", keywords: ["football", "sport"] },
  { emoji: "⚾", keywords: ["baseball", "sport"] },
  { emoji: "🎾", keywords: ["tennis", "sport"] },
  { emoji: "🏐", keywords: ["volleyball", "sport"] },
  { emoji: "🎱", keywords: ["pool", "billiards", "sport"] },
  { emoji: "🏓", keywords: ["ping", "pong", "sport"] },
  { emoji: "🥊", keywords: ["boxing", "sport"] },
  { emoji: "🎯", keywords: ["target", "dart", "goal"] },
  { emoji: "🎮", keywords: ["game", "controller", "play"] },
  { emoji: "🎲", keywords: ["dice", "game", "random"] },
  { emoji: "🎵", keywords: ["music", "note"] },
  { emoji: "🎸", keywords: ["guitar", "music"] },
  { emoji: "🎬", keywords: ["movie", "clapper", "film"] },
  { emoji: "🎨", keywords: ["art", "palette", "design"] },
  { emoji: "📷", keywords: ["camera", "photo"] },
  { emoji: "💻", keywords: ["laptop", "computer", "tech"] },
  { emoji: "📱", keywords: ["phone", "mobile", "tech"] },
  { emoji: "⌨️", keywords: ["keyboard", "tech"] },
  { emoji: "🖥️", keywords: ["desktop", "computer", "tech"] },
  { emoji: "🔧", keywords: ["wrench", "tool", "fix"] },
  { emoji: "🔨", keywords: ["hammer", "tool", "build"] },
  { emoji: "🪛", keywords: ["screwdriver", "tool"] },
  { emoji: "⚙️", keywords: ["gear", "settings", "config"] },
  { emoji: "🔑", keywords: ["key", "lock", "access"] },
  { emoji: "🔒", keywords: ["lock", "secure", "private"] },
  { emoji: "🔓", keywords: ["unlock", "open"] },
  { emoji: "📎", keywords: ["paperclip", "attach", "attachment"] },
  { emoji: "📌", keywords: ["pin", "pushpin", "important"] },
  { emoji: "✂️", keywords: ["scissors", "cut"] },
  { emoji: "📝", keywords: ["memo", "note", "write"] },
  { emoji: "📄", keywords: ["page", "document", "paper"] },
  { emoji: "📃", keywords: ["page", "curl", "document"] },
  { emoji: "📋", keywords: ["clipboard", "list", "tasks"] },
  { emoji: "📁", keywords: ["folder", "file"] },
  { emoji: "📂", keywords: ["folder", "open", "file"] },
  { emoji: "📦", keywords: ["package", "box", "shipping"] },
  { emoji: "📫", keywords: ["mailbox", "mail", "letter"] },
  { emoji: "✉️", keywords: ["envelope", "mail", "letter", "email"] },
  { emoji: "📧", keywords: ["email", "mail"] },
  { emoji: "📨", keywords: ["incoming", "mail", "letter"] },
  { emoji: "📩", keywords: ["envelope", "arrow", "mail"] },
  { emoji: "📬", keywords: ["mailbox", "mail"] },
  { emoji: "📮", keywords: ["postbox", "mail"] },
  { emoji: "🏠", keywords: ["house", "home"] },
  { emoji: "🏢", keywords: ["office", "building", "work"] },
  { emoji: "🏭", keywords: ["factory", "building"] },
  { emoji: "🏪", keywords: ["store", "shop"] },
  { emoji: "🛒", keywords: ["cart", "shopping"] },
  { emoji: "💼", keywords: ["briefcase", "work", "business"] },
  { emoji: "💰", keywords: ["money", "bag", "finance"] },
  { emoji: "💳", keywords: ["credit", "card", "payment"] },
  { emoji: "💡", keywords: ["bulb", "idea", "light"] },
  { emoji: "📊", keywords: ["chart", "bar", "stats"] },
  { emoji: "📈", keywords: ["chart", "up", "growth"] },
  { emoji: "📉", keywords: ["chart", "down", "decline"] },
  { emoji: "🧮", keywords: ["calculator", "math"] },
  { emoji: "🎓", keywords: ["graduation", "education", "school"] },
  { emoji: "📚", keywords: ["books", "library", "read"] },
  { emoji: "🔬", keywords: ["microscope", "science"] },
  { emoji: "🧪", keywords: ["test", "tube", "science"] },
  { emoji: "🌍", keywords: ["earth", "globe", "world"] },
  { emoji: "🌎", keywords: ["earth", "americas", "globe"] },
  { emoji: "🌏", keywords: ["earth", "asia", "globe"] },
  { emoji: "🗺️", keywords: ["map", "travel"] },
  { emoji: "🧭", keywords: ["compass", "navigation"] },
  { emoji: "🚗", keywords: ["car", "drive", "transport"] },
  { emoji: "🚕", keywords: ["taxi", "transport"] },
  { emoji: "🚌", keywords: ["bus", "transport"] },
  { emoji: "🚎", keywords: ["trolley", "bus", "transport"] },
  { emoji: "🏎️", keywords: ["race", "car", "fast"] },
  { emoji: "🚓", keywords: ["police", "car"] },
  { emoji: "🚑", keywords: ["ambulance", "medical"] },
  { emoji: "🚒", keywords: ["fire", "truck"] },
  { emoji: "🚲", keywords: ["bike", "bicycle", "cycle"] },
  { emoji: "🛵", keywords: ["scooter", "transport"] },
  { emoji: "✈️", keywords: ["airplane", "plane", "travel", "flight"] },
  { emoji: "🚀", keywords: ["rocket", "launch", "space"] },
  { emoji: "🛸", keywords: ["ufo", "space"] },
  { emoji: "🚁", keywords: ["helicopter", "transport"] },
  { emoji: "🛳️", keywords: ["ship", "cruise", "travel"] },
  { emoji: "⛵", keywords: ["sailboat", "boat"] },
  { emoji: "🚂", keywords: ["train", "transport"] },
  { emoji: "🏖️", keywords: ["beach", "vacation"] },
  { emoji: "🏔️", keywords: ["mountain", "nature"] },
  { emoji: "⛺", keywords: ["tent", "camping"] },
  { emoji: "🎉", keywords: ["party", "celebrate", "tada"] },
  { emoji: "🎁", keywords: ["gift", "present"] },
  { emoji: "🎈", keywords: ["balloon", "party"] },
  { emoji: "🏆", keywords: ["trophy", "win", "award"] },
  { emoji: "🥇", keywords: ["gold", "medal", "first"] },
  { emoji: "✅", keywords: ["check", "done", "complete", "yes"] },
  { emoji: "❌", keywords: ["cross", "no", "wrong", "delete"] },
  { emoji: "⚠️", keywords: ["warning", "alert", "caution"] },
  { emoji: "❓", keywords: ["question", "help"] },
  { emoji: "❗", keywords: ["exclamation", "important"] },
  { emoji: "💯", keywords: ["hundred", "perfect", "score"] },
  { emoji: "🔔", keywords: ["bell", "notification", "alert"] },
  { emoji: "🔕", keywords: ["mute", "bell", "silent"] },
  { emoji: "⏰", keywords: ["alarm", "clock", "time"] },
  { emoji: "📅", keywords: ["calendar", "date", "schedule"] },
  { emoji: "🗓️", keywords: ["calendar", "spiral", "date"] },
  { emoji: "⏳", keywords: ["hourglass", "wait", "time"] },
  { emoji: "🕐", keywords: ["clock", "time", "one"] },
];

export function filterEntityIconEmojis(query: string): EntityIconEmojiEntry[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) {
    return ENTITY_ICON_EMOJIS;
  }

  return ENTITY_ICON_EMOJIS.filter((entry) => {
    if (entry.emoji.includes(normalized)) {
      return true;
    }

    return entry.keywords.some((keyword) => keyword.includes(normalized));
  });
}
