import { StyleSheet } from "react-native";

import { colors, spacing } from "./theme";

export const ui = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  centered: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  chrome: {
    paddingHorizontal: spacing.screenX,
    paddingVertical: spacing.chromeY,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    backgroundColor: colors.background,
  },
  chromeText: {
    color: colors.muted,
    fontSize: 12,
    flex: 1,
  },
  chromeAction: {
    color: colors.foreground,
    fontWeight: "600",
    fontSize: 14,
  },
  hint: {
    paddingHorizontal: spacing.screenX,
    paddingTop: 14,
    paddingBottom: 8,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  empty: {
    padding: spacing.screenX,
    color: colors.muted,
    fontSize: 14,
  },
  error: {
    padding: spacing.screenX,
    color: colors.danger,
    fontSize: 14,
  },
  sectionHeader: {
    paddingHorizontal: spacing.screenX,
    paddingTop: 18,
    paddingBottom: 6,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "500",
    letterSpacing: 0.2,
    backgroundColor: colors.background,
  },
  row: {
    paddingHorizontal: spacing.screenX,
    paddingVertical: spacing.rowY,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  rowIcon: {
    marginTop: 3,
  },
  rowBody: {
    flex: 1,
    minWidth: 0,
  },
  rowTitleLine: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 10,
    minWidth: 0,
  },
  rowTitle: {
    flex: 1,
    minWidth: 0,
    color: colors.foreground,
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 21,
  },
  rowId: {
    flexShrink: 0,
    color: colors.muted,
    fontSize: 13,
    fontVariant: ["tabular-nums"],
    fontFamily: "Menlo",
  },
  rowMeta: {
    color: colors.muted,
    marginTop: 3,
    fontSize: 12,
    lineHeight: 16,
  },
  pillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    maxWidth: "100%",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 999,
  },
  pillLabel: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 15,
    flexShrink: 1,
  },
  detailId: {
    color: colors.muted,
    fontSize: 13,
    fontFamily: "Menlo",
    fontVariant: ["tabular-nums"],
  },
  detailTitle: {
    color: colors.foreground,
    fontSize: 24,
    fontWeight: "600",
    lineHeight: 30,
  },
  detailDescription: {
    paddingHorizontal: spacing.screenX,
    paddingTop: 4,
    color: colors.foreground,
    fontSize: 15,
    lineHeight: 22,
  },
  propertyRow: {
    paddingHorizontal: spacing.screenX,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  propertyLabel: {
    color: colors.muted,
    fontSize: 14,
    width: 88,
  },
  propertyValue: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
  },
  propertyValueText: {
    color: colors.foreground,
    fontSize: 14,
    flexShrink: 1,
    textAlign: "right",
  },
  title: {
    color: colors.foreground,
    fontSize: 24,
    fontWeight: "600",
  },
  body: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  input: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.foreground,
  },
  button: {
    backgroundColor: colors.buttonBg,
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: "center",
  },
  buttonLabel: {
    color: colors.buttonText,
    fontWeight: "600",
    fontSize: 15,
  },
  buttonSecondary: {
    backgroundColor: colors.githubBg,
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: "center",
  },
  buttonSecondaryLabel: {
    color: colors.foreground,
    fontWeight: "600",
    fontSize: 15,
  },
});
